config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :scratch_projects, only: [:index]
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'uri'
  require 'net/http'
  require 'json'
  require 'time'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
    
  end
end

app/controllers/scratch_projects_controller.rb
class ScratchProjectsController < ApplicationController
  
  def index
    @projects_of_all = []
    students = Student.all
    students.each do |student|
      url ="https://api.scratch.mit.edu/users/#{student.scratch_username}/projects"
      # url = "https://api.scratch.mit.edu/users/t-okazaki"
      uri = URI.parse(url)
      res = Net::HTTP.get(uri)
      res = JSON.parse(res)
      @projects_of_all.push(res)
    end
  end
  
  def show
    
  end
  
  private
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end
  
  def show
    @student = Student.find(params[:id])
    url ="https://api.scratch.mit.edu/users/#{@student.scratch_username}/projects"
    # url = "https://api.scratch.mit.edu/users/t-okazaki"
    uri = URI.parse(url)
    res = Net::HTTP.get(uri)
    res = JSON.parse(res)
    @projects = res
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.save
    redirect_to students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to students_path
  end
  
  def destroy
    student = Student.find(params[:id])
    student.destroy
    redirect_to students_path
  end
  
  private
  
  def student_params
    params.require(:student).permit(:scratch_username, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/scratch_students_helper.rb
module ScratchStudentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<h1>TOPページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんなのScratchさくひん</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container clear">
        <div class="header-left">
          <h1 class="header-logo">みんなのScratch</h1>
        </div>
        <div class="header-right">
          <nav>
            <ul class="header-nav clear">
              <li class= 'header-nav-item'><%= link_to 'Home', root_path %></li>
              <li class= 'header-nav-item'><%= link_to 'About', about_path %></li>
              <li class= 'header-nav-item'><%= link_to 'Sign up', root_path %></li>
              <li class= 'header-nav-item'><%= link_to 'Login', root_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>

    </footer>
  </body>
</html>

app/views/scratch_projects/index.html.erb
<h1>プロジェクト一覧</h1>
<h3>最新の順番だとなお良い</h3>
<% @projects_of_all.each do |projects_of_one| %>
  <% projects_of_one.each do |project| %>
    <div><%= project['title'] %></div>
    <div><%= image_tag project['images']["282x218"] %></div>
  <% end %>
<% end %>

app/views/students/edit.html.erb
<h2>生徒情報変更</h2>
<%= form_with model: @student, local: true do |f| %>
  <div>
    <%= f.label :scratch_username, 'Scratchユーザー名' %>
  </div>
  <div>
    <%= f.text_field :scratch_username %>
  </div>
  <div>
    <%= f.label :name, '生徒氏名' %>
  </div>
  <div>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit '更新' %>
  </div>
<% end %>

app/views/students/index.html.erb
<h2>生徒一覧</h2>
<table>
  <thead>
    <tr>
      <th>scratchアカウント</th>
      <th>氏名</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td>
        <%= link_to student_path(student.id) do %>
          <%= student.scratch_username %>
        <% end %>
      </td>
      <td><%= student.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h2>生徒新規登録</h2>
<%= form_with model: @student, local: true do |f| %>
  <div>
    <%= f.label :scratch_username, 'Scratchユーザー名' %>
  </div>
  <div>
    <%= f.text_field :scratch_username %>
  </div>
  <div>
    <%= f.label :name, '生徒氏名' %>
  </div>
  <div>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit '登録' %>
  </div>
<% end %>

app/views/students/show.html.erb
<h2>生徒のプロジェクト一覧<h2>
<div>
  <p><%= @student.name %></p>
  <p><%= @student.scratch_username %></p>
</div>
<div>
  <table>
    <thead>
      <tr>
        <th></th>
        <th>プロジェクト名</th>
        <th>作成日</th>
        <th>更新日</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
          <tr>
            <td><%= image_tag project['image'] %></td>
            <td>
              <%= link_to "https://scratch.mit.edu/projects/#{project['id']}/", target: :_blank, rel: "noopener noreferrer" do %>
                <%= project['title'] %>
              <% end %>
            </td>
            <td>
              <%= (Time.parse(project['history']['created']) + 32400).strftime('%Y/%m/%d at %H:%M') %></td>
            <td><%= (Time.parse(project['history']['modified']) + 32400).strftime('%Y/%m/%d at %H:%M') %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>